### ISSUE TITLE
Gitorious sunset "end of May"

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew-head-only#117]
"System notice: Gitorious is being acquired by GitLab and gitorious.org will shut down end of May."
—banner on Gitorious

Affected formulæ in the homebrew-head-only tap:

- [x] qt-mobility
- [x] willgit

(See also Homebrew/homebrew#39176 for core formulæ affected by the closure.)

**Comment by mistydemeo** [comment]
The blog post is currently down, but my understanding is Archive Team have offered to take over Gitorious and keep it operating indefinitely as a read-only archive of its contents: http://archiveteam.org/index.php?title=Gitorious#Archives

**Comment by L2G** [comment]
Ahhh. Good to know! (I take it Archive Team is distinct from, and not to be confused with, the [Internet Archive](https://archive.org/)?)

In the case of qt-mobility, I imagine the Qt project will want to move it to an active repo before Gitorious shuts down..

In the case of willgit, it hasn't seen an update in maybe 5 years, so the read-only archive would be appropriate and good. (In such a case, is willgit more appropriate to keep in the head-only tap or the boneyard?)

**Comment by mistydemeo** [comment]
> (I take it Archive Team is distinct from, and not to be confused with, the Internet Archive?)

Yep, most of their projects end up stored on the Internet Archive but they're not formally related outside of Jason Scott. The Gitorious project's pure Archive Team as far as I know.

> In the case of qt-mobility, I imagine the Qt project will want to move it to an active repo before Gitorious shuts down..

I sure hope so! Any sign of movement on their end?

> (In such a case, is willgit more appropriate to keep in the head-only tap or the boneyard?)

As long as willgit still builds, imo keeping it here is fine!

**Comment by DomT4** [comment]
`qt-mobility` no longer [builds for me](https://gist.github.com/anonymous/4519a9a3084ffbefc1c9), so I'm tempted to scrap it given the URL has been dead for at least 3 months without anyone noticing. No upstream activity in 15 months.

**Comment by L2G** [comment]
At this writing, Gitorious.org is showing the following message: "Gitorious.org is migrating all the repositories to [Internet Archive](https://archive.org/)."

**Comment by bfontaine** [comment]
`willgit` has been mirrored, I updated the formula.
