### ISSUE TITLE
brew install smpeg fails with error (autogen.sh; aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in')

### ISSUE THREAD

**Issue by hanleybrand** [Homebrew/homebrew-head-only#126]
I'm getting this error when I try `brew install -v --HEAD smpeg` and it's failing to build - I'm not sure what to do next 

I've tried brew update, doctor, upgrade, cleanup, etc. 

autom4te is installed to /usr/local/bin/autom4te (I added 001_shell_out.sh to the gist-log to show a few paths) 

```bash
==> ./autogen.sh
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
sh: autom4te: command not found
aclocal: error: echo failed with exit status: 127
couldn't understand kern.osversion `14.3.0'
```

https://gist.github.com/hanleybrand/a658ad39f8e13b43054b

Thanks for any suggestions

**Comment by DomT4** [comment]
Moved to the core. `brew update && brew install smpeg`.
