### ISSUE TITLE
Can't Compile Redis-tools on 10.11.1

### ISSUE THREAD

**Issue by LikeSimple** [Homebrew/homebrew-head-only#194]
JimmydeMacBook-Pro:~ jimmy$ brew install --HEAD homebrew/head-only/redis-tools
==> Installing redis-tools from homebrew/homebrew-head-only
==> Cloning https://github.com/antirez/redis-tools.git
Cloning into '/Library/Caches/Homebrew/redis-tools--git'...
remote: Counting objects: 47, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 47 (delta 7), reused 37 (delta 5), pack-reused 0
Unpacking objects: 100% (47/47), done.
Checking connectivity... done.
==> Checking out branch master
==> make
Last 15 lines from /Users/jimmy/Library/Logs/Homebrew/redis-tools/01.make:
1 error generated.
make[1]: *** [hiredis.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [redis-stat] Error 2
make: *** Waiting for unfinished jobs....
hiredis.c:696:31: error: second argument to 'va_arg' is of incomplete type 'void'
                    va_arg(ap,void);
                              ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stdarg.h:35:50: note: expanded from macro 'va_arg'
#define va_arg(ap, type)    __builtin_va_arg(ap, type)
                                                 ^
1 error generated.
make[1]: *** [hiredis.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [redis-load] Error 2

**Comment by dunn** [comment]
Can you post `brew gist-logs redis-tools`? Thanks!

**Comment by TGVarik** [comment]
Same issue here. `gist-logs` is [here](https://gist.github.com/TGVarik/c0b62b87dc87a1a5e04c).

**Comment by TGVarik** [comment]
Possibly due to `redis-tools` being some 6 years old.

**Comment by bfontaine** [comment]
I was able to compile it with the following changes:

```diff
diff --git a/redis-tools.rb b/redis-tools.rb
index bee04b3..acefd13 100644
--- a/redis-tools.rb
+++ b/redis-tools.rb
@@ -2,10 +2,28 @@ class RedisTools < Formula
   head "https://github.com/antirez/redis-tools.git"
   homepage "https://github.com/antirez/redis-tools"
 
+  patch :DATA
+
   def install
     # Architecture isn't detected correctly on 32bit Snow Leopard without help
     ENV["OBJARCH"] = MacOS.prefer_64_bit? ? "-arch x86_64" : "-arch i386"
+    # -rdynamic is not supported on OS X
+    inreplace "Makefile", "-rdynamic", ""
     system "make"
     bin.install ["redis-load", "redis-stat"]
   end
 end
+
+__END__
+Based on https://trac.macports.org/browser/trunk/dports/databases/redis/files/patch-hiredis.c.diff?rev=85937
+--- a/deps/hiredis/hiredis.c 2011-10-17 17:03:17.000000000 -0400
++++ b/deps/hiredis/hiredis.c 2011-10-17 17:03:17.000000000 -0400
+@@ -693,7 +693,7 @@
+                     }
+ 
+                     /* Consume and discard vararg */
+-                    va_arg(ap,void);
++                    va_arg(ap,char*);
+                 }
+             }
+             touched = 1;
```

[`redis-tools` is abandoned](https://github.com/antirez/redis-tools/issues/9#issuecomment-157329972); I’ll make a pull-request upstream just in case.
