### ISSUE TITLE
depot_tools doesn't install all tools

### ISSUE THREAD

**Issue by gsnedders** [Homebrew/homebrew-head-only#211]
Given the expected workflow using depot_tools is to have the whole thing in PATH, we should be installing all executables from it. Currently we have so few that you can't even follow [the Chromium instructions](https://www.chromium.org/developers/how-tos/get-the-code) to checkout their repo. PR to soon follow.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
