### ISSUE TITLE
f2c  /bin/sh: ./xsum: Permission denied

### ISSUE THREAD

**Issue by Foadsf** [Homebrew/homebrew-head-only#255]
for f2c installation from [this formula](https://github.com/Homebrew/homebrew-head-only/blob/a2b835722e6d463203e819197a95a2999812e51f/f2c.rb)
as it has been explained [here](http://superuser.com/questions/1091886/fortran-compiler-installation-instructions-for-os-x) there is an issue on mac OS X. the `xsum` inside the `src` folder must be deleted before compiling. I tried to edit the formula but github says: 

> you must be on a branch to make or proposed changes to this file

I'm not sure what should I do, but please fix this. you may also see other examples of f2c installation scrips here and [here](http://hpc.sourceforge.net/buildf2c) and [here](install_f2c_linux.csh) for linux and [this one for mac](http://www.webmo.net/support/download/install_f2c_osx.csh)

**Comment by bfontaine** [comment]
Sorry I just saw your issue. `f2c` has been moved in [`homebrew/boneyard`](https://github.com/Homebrew/homebrew-boneyard/blob/master/f2c.rb) three months ago because we’re deprecating this repo and we don’t have a stable release for it.
