### ISSUE TITLE
--HEAD?

### ISSUE THREAD

**Issue by hurrymaplelad** [Homebrew/homebrew-head-only#86]
When I try

```
$ brew install homebrew/head-only/git-hooks
```

as suggested in the [README](https://github.com/Homebrew/homebrew-head-only#how-do-i-install-these-formulae), I get 

```
Error: git-hooks is a head-only formula
Install with `brew install --HEAD git-hooks`
```

Are the docs outdated?

**Comment by hurrymaplelad** [comment]
Actually, looks like I need both:

```sh
$ brew install --HEAD homebrew/head-only/git-hooks
```

**Comment by jacknagel** [comment]
One must pass `--HEAD` to install a head-only formula (this is to make sure you know what you're getting into). I'll update the readme.

**Comment by hurrymaplelad** [comment]
Makes sense, thanks!
