### ISSUE TITLE
A way to install from a branch other than master?

### ISSUE THREAD

**Issue by trusktr** [Homebrew/homebrew-head-only#95]
`brew install --HEAD` installs from a branch, I'm guessing master. Is there a way to specify a branch?

**Comment by jacknagel** [comment]
It can be specified in the formula. If it's omitted, master is assumed.

```rb
head "...", :branch => "branch_name"
```

**Comment by trusktr** [comment]
I discovered brew edit <package>. Thanks!

/#!/JoePea
